import {
  Bath,
  Wifi,
  Droplets,
  TreePine,
  UtensilsCrossed,
  Umbrella,
  Home,
  Eye,
  Building,
  Trees,
  Users,
  Waves,
  Martini,
  Thermometer,
  Moon,
} from "lucide-react";

// Define the house data for all phases
export const phaseData = [
  {
    id: "phase-1",
    title: "Phase I",
    description:
      "Keeth House Phase I is a cozy and intimate property that accommodates three of our beautiful houses. With vibrant trees and foliage covering almost every inch of the ground, the property is designed to make you feel relaxed from the moment you step in. We have a kitchen/diner right within the premises where you are welcome to come in and relish a hearty homemade breakfast or a hot beverage.",
    houses: [
      {
        id: "keeth-house-1",
        propertyId: 7843,
        name: "Keeth House - I",
        description:
          "Our very first creation will take you back to the traditional houses of Tamil Nadu in the 90s. The two-level house with a sprawling porch or 'thinnai' at the entrance, is ideal for a small group of friends or a family of four.",
        images: [
          "/images/keeth-house-i/1.jpg",
          "/images/keeth-house-i/2.jpg",
          "/images/keeth-house-i/3.jpg",
          "/images/keeth-house-i/4.jpg",
          "/images/keeth-house-i/5.jpg",
          "/images/keeth-house-i/6.jpg",
          "/images/keeth-house-i/7.jpg",
          "/images/keeth-house-i/8.jpg",
          "/images/keeth-house-i/9.jpg",
          "/images/keeth-house-i/10.jpg",
          "/images/keeth-house-i/11.jpg",
          "/images/keeth-house-i/12.jpg",
          "/images/keeth-house-i/13.jpg",
          "/images/keeth-house-i/14.jpg",
          "/images/keeth-house-i/15.jpg",
          "/images/keeth-house-i/16.jpg",
          "/images/keeth-house-i/17.jpg",
          "/images/keeth-house-i/18.jpg",
          "/images/keeth-house-i/19.jpg",
          "/images/keeth-house-i/20.jpg",
          "/images/keeth-house-i/21.jpg",
        ],
        specializations: [
          { name: "Forest View", icon: Trees },
          { name: "WiFi", icon: Wifi },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Duplex", icon: Home },
        ],
        map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8'
      },
      {
        id: "keeth-house-2",
        propertyId: 7843,
        name: "Keeth House - II",
        description:
          "The two-level, octagon-shaped house is a multifunctional house designed to meet all your needs. Whether you're seeking a long workcation or just a weekend getaway with friends, Keeth House II is the perfect destination.",
        images: [
          "/images/keeth-house-ii/1.jpg",
          "/images/keeth-house-ii/2.jpg",
          "/images/keeth-house-ii/3.jpg",
          "/images/keeth-house-ii/4.jpg",
          "/images/keeth-house-ii/5.jpg",
          "/images/keeth-house-ii/6.jpg",
          "/images/keeth-house-ii/7.jpg",
          "/images/keeth-house-ii/8.jpg",
          "/images/keeth-house-ii/9.jpg",
          "/images/keeth-house-ii/10.jpg",
          "/images/keeth-house-ii/11.jpg",
          "/images/keeth-house-ii/12.jpg",
          "/images/keeth-house-ii/13.jpg",
          "/images/keeth-house-ii/14.jpg",
          "/images/keeth-house-ii/15.jpg",
          "/images/keeth-house-ii/16.jpg",
          "/images/keeth-house-ii/17.jpg",
          "/images/keeth-house-ii/18.jpg",
          "/images/keeth-house-ii/19.jpg",
          "/images/keeth-house-ii/20.jpg",
          "/images/keeth-house-ii/21.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Duplex", icon: Home },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "WiFi", icon: Wifi },
        ],
        map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8'
      },
      {
        id: "keeth-house-3",
        propertyId: 7843,
        name: "Keeth House - III",
        description:
          "The house is slightly tucked away to give you an off-the-grid experience. With picturesque views during the day and the soft warm glow of lights at night, it's an ideal destination for an intimate romantic getaway.",
        images: [
          "/images/keeth-house-iii/1.jpg",
          "/images/keeth-house-iii/2.jpg",
          "/images/keeth-house-iii/3.jpg",
          "/images/keeth-house-iii/4.jpg",
          "/images/keeth-house-iii/5.jpg",
          "/images/keeth-house-iii/6.jpg",
          "/images/keeth-house-iii/7.jpg",
          "/images/keeth-house-iii/8.jpg",
          "/images/keeth-house-iii/9.jpg",
          "/images/keeth-house-iii/10.jpg",
          "/images/keeth-house-iii/11.jpg",
          "/images/keeth-house-iii/12.jpg",
          "/images/keeth-house-iii/13.jpg",
          "/images/keeth-house-iii/14.jpg",
          "/images/keeth-house-iii/15.jpg",
          "/images/keeth-house-iii/16.jpg",
          "/images/keeth-house-iii/17.jpg",
          "/images/keeth-house-iii/18.jpg",
          "/images/keeth-house-iii/19.jpg",
          "/images/keeth-house-iii/20.jpg",
          "/images/keeth-house-iii/21.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Forest View", icon: Trees },
          { name: "Duplex", icon: Home },
          { name: "WiFi", icon: Wifi },
        ],
         map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8'
      },
    ],
  },
  {
    id: "phase-2",
    title: "Phase II",
    description:
      "Located 2km away from Keeth House Phase I, the secluded property boasts four charming houses each with its unique attributes. The high ceilings of the houses along with the lush tree cover across the expansive land create a cool and serene atmosphere both inside and out. The verdant setting with vibrant flora and fauna makes Keeth House Phase II a paradise for nature lovers.",
    houses: [
      {
        id: "keeth-house-4",
        propertyId: 7860,
        name: "Keeth House - IV",
        description:
          "The charming house, which efficiently combines the best features of all our houses, is best suited for couples seeking a quiet nature retreat. The high thatched roof and large windows with gorgeous views make the interiors spacious and airy without compromising on comfort.",
        images: [
          "/images/keeth-house-iv/1.jpg",
          "/images/keeth-house-iv/2.jpg",
          "/images/keeth-house-iv/3.jpg",
          "/images/keeth-house-iv/4.jpg",
          "/images/keeth-house-iv/5.jpg",
          "/images/keeth-house-iv/6.jpg",
          "/images/keeth-house-iv/7.jpg",
          "/images/keeth-house-iv/8.jpg",
          "/images/keeth-house-iv/9.jpg",
          "/images/keeth-house-iv/10.jpg",
          "/images/keeth-house-iv/11.jpg",
          "/images/keeth-house-iv/12.jpg",
          "/images/keeth-house-iv/13.jpg",
          "/images/keeth-house-iv/14.jpg",
          "/images/keeth-house-iv/15.jpg",
          "/images/keeth-house-iv/16.jpg",
          "/images/keeth-house-iv/17.jpg",
          "/images/keeth-house-iv/18.jpg",
          "/images/keeth-house-iv/19.jpg",
          "/images/keeth-house-iv/20.jpg",
          "/images/keeth-house-iv/21.jpg",
          "/images/keeth-house-iv/22.jpg",
          "/images/keeth-house-iv/23.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Garden View", icon: TreePine },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Outdoor Dining", icon: Umbrella },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8'
      },
      {
        id: "keeth-house-5",
        propertyId: 7860,
        name: "Keeth House - V",
        description:
          "One of our biggest houses, this house symbolizes rustic elegance. With a bathtub inside and an outdoor shower in the backyard, you are sure to enjoy a unique stay with your loved one. It has a spacious courtyard at the entrance with ample seating for you to relax and enjoy the crisp air.",
        images: [
          "/images/keeth-house-v/1.jpg",
          "/images/keeth-house-v/2.jpg",
          "/images/keeth-house-v/3.jpg",
          "/images/keeth-house-v/4.jpg",
          "/images/keeth-house-v/5.jpg",
          "/images/keeth-house-v/6.jpg",
          "/images/keeth-house-v/7.jpg",
          "/images/keeth-house-v/8.jpg",
          "/images/keeth-house-v/9.jpg",
          "/images/keeth-house-v/10.jpg",
          "/images/keeth-house-v/11.jpg",
          "/images/keeth-house-v/12.jpg",
          "/images/keeth-house-v/13.jpg",
          "/images/keeth-house-v/14.jpg",
          "/images/keeth-house-v/15.jpg",
          "/images/keeth-house-v/16.jpg",
          "/images/keeth-house-v/17.jpg",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "Open Shower", icon: Droplets },
          { name: "Portico", icon: Umbrella },
          { name: "Garden View", icon: TreePine },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8'
      },
      {
        id: "keeth-house-6",
        propertyId: 7860,
        name: "Keeth House - VI",
        description:
          "The idyllic setting and unique design of the house make it a blissful retreat, perfect for sipping drinks by the pond or hosting a cookout party with your friends. As you walk towards the house, you are greeted by a small, pristine pond at the front, exclusive to this house.",
        images: [
          "/images/keeth-house-vi/1.jpg",
          "/images/keeth-house-vi/2.jpg",
          "/images/keeth-house-vi/3.jpg",
          "/images/keeth-house-vi/4.jpg",
          "/images/keeth-house-vi/5.jpg",
          "/images/keeth-house-vi/6.jpg",
          "/images/keeth-house-vi/7.jpg",
          "/images/keeth-house-vi/8.jpg",
          "/images/keeth-house-vi/9.jpg",
          "/images/keeth-house-vi/10.jpg",
          "/images/keeth-house-vi/11.jpg",
          "/images/keeth-house-vi/12.jpg",
          "/images/keeth-house-vi/13.jpg",
          "/images/keeth-house-vi/14.jpg",
          "/images/keeth-house-vi/15.jpg",
          "/images/keeth-house-vi/16.jpg",
          "/images/keeth-house-vi/17.jpg",
          "/images/keeth-house-vi/18.jpg",
          "/images/keeth-house-vi/19.jpg",
          "/images/keeth-house-vi/20.jpg",
          "/images/keeth-house-vi/21.jpg",
          "/images/keeth-house-vi/22.jpg",
          "/images/keeth-house-vi/23.jpg",
          "/images/keeth-house-vi/24.jpg",
          "/images/keeth-house-vi/25.jpg",
          "/images/keeth-house-vi/26.jpg",
          "/images/keeth-house-vi/27.jpg",
        ],
        specializations: [
          { name: "Family Friendly", icon: Users },
          { name: "Waterbody", icon: Waves },
          { name: "Garden View", icon: TreePine },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8'
      },
      {
        id: "khaya-nest",
        propertyId: 7860,
        name: "The Khaya Nest",
        description:
          "We took connecting with nature to another level - a level that's 10 meters above the ground! Khaya Nest is our very own Tree House built around the majestic African Mahogany tree known as the 'Khaya' tree. Built with intricate planning and care, Khaya Nest will give you a unique, safe, and adventurous experience.",
        images: [
          "/images/khaya-nest/1.jpg",
          "/images/khaya-nest/2.jpg",
          "/images/khaya-nest/3.jpg",
          "/images/khaya-nest/4.jpg",
          "/images/khaya-nest/5.jpg",
          "/images/khaya-nest/6.jpg",
          "/images/khaya-nest/7.jpg",
          "/images/khaya-nest/8.jpg",
          "/images/khaya-nest/9.jpg",
          "/images/khaya-nest/10.jpg",
          "/images/khaya-nest/11.jpg",
          "/images/khaya-nest/12.jpg",
          "/images/khaya-nest/13.jpg",
          "/images/khaya-nest/14.jpg",
          "/images/khaya-nest/15.jpg",
          "/images/khaya-nest/16.jpg",
          "/images/khaya-nest/17.jpg",
          "/images/khaya-nest/18.jpg",
          "/images/khaya-nest/19.jpg",
          "/images/khaya-nest/20.jpg",
          "/images/khaya-nest/21.jpg",
          "/images/khaya-nest/22.jpg",
          "/images/khaya-nest/23.jpg",
          "/images/khaya-nest/24.jpg",
          "/images/khaya-nest/25.jpg",
          "/images/khaya-nest/26.jpg",
        ],
        specializations: [
          { name: "Tree House", icon: TreePine },
          { name: "Open Shower", icon: Droplets },
          { name: "Forest View", icon: Trees },
          { name: "Balcony", icon: Umbrella },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8'
      },
    ],
  },
  {
    id: "phase-3",
    title: "Phase III",
    description:
      "Our newest collection of unique eco-houses, combining sustainable living with modern comforts and amenities.",
    houses: [
      {
        id: "keeth-house-7",
        propertyId: 9930,
        name: "Keeth House - VII",
        description:
          "Keeth House VII offers a serene escape. The open dining and kitchenette area invites you to enjoy meals under the stars or the soft morning light, connecting deeply with nature. Climb the rustic ladder to a secluded balcony, where birdsong and rustling leaves set the perfect tone for quiet moments. Refresh in the open-to-the-sky shower, surrounded by lush greenery, or unwind in the spacious restroom designed for comfort.",
        images: [
          "/images/keeth-house-vii/1.JPG",
          "/images/keeth-house-vii/2.JPG",
          "/images/keeth-house-vii/3.JPG",
          "/images/keeth-house-vii/4.JPG",
          "/images/keeth-house-vii/5.JPG",
          "/images/keeth-house-vii/6.JPG",
          "/images/keeth-house-vii/7.JPG",
          "/images/keeth-house-vii/8.JPG",
          "/images/keeth-house-vii/9.JPG",
          "/images/keeth-house-vii/10.JPG",
          "/images/keeth-house-vii/9.JPG",
          "/images/keeth-house-vii/10.JPG",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Outdoor Shower", icon: Droplets },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
          { name: "Forest View", icon: Trees },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "keeth-house-8",
        propertyId: 9930,
        name: "Keeth House - VIII",
        description:
          "Coming Soon - Keeth House VIII will offer a serene escape with open dining and kitchenette area, inviting you to enjoy meals under the stars or the soft morning light, connecting deeply with nature.",
        images: [
          "/images/coming-soon.jpg?height=600&width=800&text=Coming Soon",
        ],
        specializations: [
          { name: "Swimming Pool", icon: Waves },
          { name: "Family Friendly", icon: Users },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Bar Counter", icon: Martini },
        ],
        comingSoon: true,
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "keeth-house-9",
        propertyId: 9930,
        name: "Keeth House - IX",
        description:
          "Keeth House IX stands elevated, offering a unique retreat in nature. The house is thoughtfully divided into two sections, with large windows framing lush greenery and filling the space with natural light. At its heart is a kitchenette with an island counter, perfect for cooking, gathering, and sharing meals. The separate bedroom opens onto a private balcony, an ideal spot to soak in the sunrise or starlit sky.",
        images: [
          "/images/keeth-house-ix/1.JPG",
          "/images/keeth-house-ix/2.JPG",
          "/images/keeth-house-ix/3.JPG",
          "/images/keeth-house-ix/4.JPG",
          "/images/keeth-house-ix/5.JPG",
          "/images/keeth-house-ix/6.JPG",
          "/images/keeth-house-ix/7.JPG",
          "/images/keeth-house-ix/8.JPG",
          "/images/keeth-house-ix/9.JPG",
          "/images/keeth-house-ix/10.JPG",
        ],
        specializations: [
          { name: "Waterbody", icon: Waves },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Shower View", icon: Eye },
          { name: "MudHouse", icon: Home },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "keeth-house-10",
        propertyId: 9930,
        name: "Keeth House - X",
        description:
          "Coming Soon - Keeth House X will stand elevated, offering a unique retreat in nature. The house will be thoughtfully divided into sections, with large windows framing lush greenery and filling the space with natural light.",
        images: [
          "/images/coming-soon.jpg?height=600&width=800&text=Coming Soon",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "Shower View", icon: Eye },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
          { name: "Hammock", icon: Moon },
        ],
        comingSoon: true,
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "de-cabin",
        propertyId: 9930,
        name: "De Cabin",
        description:
          "De Cabin is a peaceful getaway, built from recycled wood to blend with nature. Perfect for conscious travelers or couples, it offers a quiet and refreshing stay. The open layout connects the living, dining, and kitchen areas, with large windows bringing in natural light and views of the greenery. A small kitchenette with an island counter makes meals easy, whether indoors or outdoors.",
        images: [
          "/images/de-cabin/1.JPG",
          "/images/de-cabin/2.JPG",
          "/images/de-cabin/3.JPG",
          "/images/de-cabin/4.JPG",
          "/images/de-cabin/5.JPG",
          "/images/de-cabin/6.JPG",
          "/images/de-cabin/7.JPG",
          "/images/de-cabin/8.JPG",
          "/images/de-cabin/9.JPG",
          "/images/de-cabin/10.JPG",
          "/images/de-cabin/11.JPG",
          "/images/de-cabin/12.JPG",
          "/images/de-cabin/13.JPG",
          "/images/de-cabin/14.JPG",
          "/images/de-cabin/15.JPG",
          "/images/de-cabin/16.JPG",
          "/images/de-cabin/17.JPG",
          "/images/de-cabin/18.JPG",
          "/images/de-cabin/19.JPG",
          "/images/de-cabin/20.JPG",
        ],
        specializations: [
          { name: "Wooden House", icon: Home },
          { name: "Open Shower", icon: Droplets },
          { name: "Bar Counter", icon: Martini },
          { name: "Fully Equipped", icon: UtensilsCrossed },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "de-villa-1",
        propertyId: 9930,
        name: "De Villa I",
        description:
          "De Villa I offers a charming retreat that blends tradition with modern comfort. The cozy living area flows into a well-equipped kitchenette, creating a warm and inviting space. Dine outdoors under a roof, surrounded by nature's soothing sounds. The tranquil bedroom, with a garden-facing bed and air conditioning, ensures restful sleep. A cozy window seat invites moments of reading or quiet reflection.",
        images: [
          "/images/de-villa-i/1.JPG",
          "/images/de-villa-i/2.JPG",
          "/images/de-villa-i/3.JPG",
          "/images/de-villa-i/4.JPG",
          "/images/de-villa-i/5.JPG",
          "/images/de-villa-i/6.JPG",
          "/images/de-villa-i/7.JPG",
          "/images/de-villa-i/8.JPG",
          "/images/de-villa-i/9.JPG",
          "/images/de-villa-i/10.JPG",
          "/images/de-villa-i/11.JPG",
          "/images/de-villa-i/12.JPG",
          "/images/de-villa-i/13.JPG",
          "/images/de-villa-i/14.JPG",
          "/images/de-villa-i/15.JPG",
          "/images/de-villa-i/16.JPG",
          "/images/de-villa-i/17.JPG",
          "/images/de-villa-i/18.JPG",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "AC", icon: Thermometer },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Outdoor Dining", icon: Umbrella },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
      {
        id: "de-villa-2",
        propertyId: 9930,
        name: "De Villa II",
        description:
          "De Villa II welcomes you with a traditional thinnai, a spacious veranda perfect for relaxing with a cup of chai. Inside, the open-plan living area flows into a well-equipped kitchenette, centered around a handcrafted wooden counter that doubles as a dining table or workspace. A unique highlight is the indoor bathroom that opens to the sky, letting you bathe under the moonlight or daylight.",
        images: [
          "/images/de-villa-ii/1.JPG",
          "/images/de-villa-ii/2.JPG",
          "/images/de-villa-ii/3.JPG",
          "/images/de-villa-ii/4.JPG",
          "/images/de-villa-ii/5.JPG",
          "/images/de-villa-ii/6.JPG",
          "/images/de-villa-ii/7.JPG",
          "/images/de-villa-ii/8.JPG",
          "/images/de-villa-ii/9.JPG",
          "/images/de-villa-ii/10.JPG",
          "/images/de-villa-ii/11.JPG",
          "/images/de-villa-ii/12.JPG",
          "/images/de-villa-ii/13.JPG",
          "/images/de-villa-ii/14.JPG",
        ],
        specializations: [
          { name: "Open Shower", icon: Droplets },
          { name: "AC", icon: Thermometer },
          { name: "Hammock", icon: Moon },
          { name: "Villa", icon: Building },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7'
      },
    ],
  },
];

// Flattened array of all houses for OurHouses component
export const houses = phaseData.reduce((acc, phase) => {
  return acc.concat(
    phase.houses.map((house) => ({
      ...house,
      location: phase.title,
      price: 150,
      phase: phase.title,
    }))
  );
}, []);
