import {
  Bath,
  Wifi,
  Droplets,
  TreePine,
  UtensilsCrossed,
  Umbrella,
  Home,
  Eye,
  Building,
  Trees,
  Users,
  Waves,
  Martini,
  Thermometer,
  Moon,
} from "lucide-react";

// Define the house data for all phases
export const phaseData = [
  {
    id: "phase-1",
    title: "Phase I",
    // description: "Keeth House Phase I is a cozy and intimate property that accommodates three of our beautiful houses. With vibrant trees and foliage covering almost every inch of the ground, the property is designed to make you feel relaxed from the moment you step in. We have a kitchen/diner right within the premises where you are welcome to come in and relish a hearty homemade breakfast or a hot beverage.",
    description:"Keeth House Phase I is reopening soon. The space is currently undergoing thoughtful updates to enhance your stay experience. We look forward to hosting you again with renewed warmth and attention to detail. Thank you for being part of our journey!",
    houses: [
      {
        id: "keeth-house-1",
        propertyId: 7843,
        name: "Keeth House - I",
        description:
          "The two-level, octagon-shaped cottage is a multifunctional house designed to meet all your needs. Whether you're seeking a long workcation or just a weekend getaway with friends, Keeth House ll is the perfect destination. \n\n The living area on the ground floor has ample seating for you and your friends to dine, hang out, and have a game night. The compact kitchen space is furnished with the necessary utensils and equipment. Additionally, there’s a designated workspace for those of you looking for a change of scenery from the usual work-from-home routine. The ambiance of the house is rustic and natural which even extends to the bathroom which has walls made of exposed brick and stone, a spacious modern shower, and some indoor foliage. \n\n The open bedroom on the first floor has two king-size beds to comfortably accommodate a group of four. The keeth roof and open ventilation ensure that the air inside is cool and fresh at all times. The sweetest spot of the house is the spacious balcony facing the forest. From birdwatching in the morning to stargazing at night, you can spend all day here with your friends, clicking instagrammable pictures and making countless memories. ",
        images: [
          "/images/keeth-house-i/1.jpg",
          "/images/keeth-house-i/2.jpg",
          "/images/keeth-house-i/3.jpg",
          "/images/keeth-house-i/4.jpg",
          "/images/keeth-house-i/5.jpg",
          "/images/keeth-house-i/6.jpg",
          "/images/keeth-house-i/7.jpg",
          "/images/keeth-house-i/8.jpg",
          "/images/keeth-house-i/9.jpg",
          "/images/keeth-house-i/10.jpg",
          "/images/keeth-house-i/11.jpg",
          "/images/keeth-house-i/12.jpg",
          "/images/keeth-house-i/13.jpg",
          "/images/keeth-house-i/14.jpg",
          "/images/keeth-house-i/15.jpg",
          "/images/keeth-house-i/16.jpg",
          "/images/keeth-house-i/17.jpg",
          "/images/keeth-house-i/18.jpg",
          "/images/keeth-house-i/19.jpg",
          "/images/keeth-house-i/20.jpg",
          "/images/keeth-house-i/21.jpg",
        ],
        specializations: [
          { name: "Forest View", icon: Trees },
          { name: "WiFi", icon: Wifi },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Duplex", icon: Home },
        ],
        map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8',
        guests: 2,
        comingSoon: true,
      },
      {
        id: "keeth-house-2",
        propertyId: 7843,
        name: "Keeth House - II",
        description:
          "The two-level, octagon-shaped cottage is a multifunctional house designed to meet all your needs. Whether you're seeking a long workcation or just a weekend getaway with friends, Keeth House ll is the perfect destination. \n\n The living area on the ground floor has ample seating for you and your friends to dine, hang out, and have a game night. The compact kitchen space is furnished with the necessary utensils and equipment. Additionally, there’s a designated workspace for those of you looking for a change of scenery from the usual work-from-home routine. The ambiance of the house is rustic and natural which even extends to the bathroom which has walls made of exposed brick and stone, a spacious modern shower, and some indoor foliage. \n\n The open bedroom on the first floor has two king-size beds to comfortably accommodate a group of four. The keeth roof and open ventilation ensure that the air inside is cool and fresh at all times. The sweetest spot of the house is the spacious balcony facing the forest. From birdwatching in the morning to stargazing at night, you can spend all day here with your friends, clicking instagrammable pictures and making countless memories. ",
        images: [
          "/images/keeth-house-ii/1.jpg",
          "/images/keeth-house-ii/2.jpg",
          "/images/keeth-house-ii/3.jpg",
          "/images/keeth-house-ii/4.jpg",
          "/images/keeth-house-ii/5.jpg",
          "/images/keeth-house-ii/6.jpg",
          "/images/keeth-house-ii/7.jpg",
          "/images/keeth-house-ii/8.jpg",
          "/images/keeth-house-ii/9.jpg",
          "/images/keeth-house-ii/10.jpg",
          "/images/keeth-house-ii/11.jpg",
          "/images/keeth-house-ii/12.jpg",
          "/images/keeth-house-ii/13.jpg",
          "/images/keeth-house-ii/14.jpg",
          "/images/keeth-house-ii/15.jpg",
          "/images/keeth-house-ii/16.jpg",
          "/images/keeth-house-ii/17.jpg",
          "/images/keeth-house-ii/18.jpg",
          "/images/keeth-house-ii/19.jpg",
          "/images/keeth-house-ii/20.jpg",
          "/images/keeth-house-ii/21.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Duplex", icon: Home },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "WiFi", icon: Wifi },
        ],
        map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8',
        guests: 4,
        comingSoon: true,
      },
      {
        id: "keeth-house-3",
        propertyId: 7843,
        name: "Keeth House - III",
        description:
          "The house is slightly tucked away to give you an off-the-grid experience. With picturesque views during the day and the soft warm glow of lights at night, it’s an ideal destination for an intimate romantic getaway.\n\n The cottage features a plush queen-size bed, comfortable seating, and a large glass wall with a stunning view of the dense forest. Continuing the theme, the bathroom also has a glass window by the shower. The house is designed to give you a ‘jungle lodge’ experience while ensuring utmost safety and privacy. \n\n The open balcony extends into the trees where you can snuggle with your partner, listen to your favorite music, and enjoy a lovely moonlit dinner. If waking up to the sight of greenery, the smell of fresh air, and the sweet sounds of birds chirping is your dream, then this is the house of your dreams!",
        images: [
          "/images/keeth-house-iii/1.jpg",
          "/images/keeth-house-iii/2.jpg",
          "/images/keeth-house-iii/3.jpg",
          "/images/keeth-house-iii/4.jpg",
          "/images/keeth-house-iii/5.jpg",
          "/images/keeth-house-iii/6.jpg",
          "/images/keeth-house-iii/7.jpg",
          "/images/keeth-house-iii/8.jpg",
          "/images/keeth-house-iii/9.jpg",
          "/images/keeth-house-iii/10.jpg",
          "/images/keeth-house-iii/11.jpg",
          "/images/keeth-house-iii/12.jpg",
          "/images/keeth-house-iii/13.jpg",
          "/images/keeth-house-iii/14.jpg",
          "/images/keeth-house-iii/15.jpg",
          "/images/keeth-house-iii/16.jpg",
          "/images/keeth-house-iii/17.jpg",
          "/images/keeth-house-iii/18.jpg",
          "/images/keeth-house-iii/19.jpg",
          "/images/keeth-house-iii/20.jpg",
          "/images/keeth-house-iii/21.jpg",
          "/images/keeth-house-iii/22.jpg",
          "/images/keeth-house-iii/23.jpg",
          "/images/keeth-house-iii/24.jpg",
          "/images/keeth-house-iii/25.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Forest View", icon: Trees },
          { name: "Duplex", icon: Home },
          { name: "WiFi", icon: Wifi },
        ],
         map: '/images/maps/Phase-I-Map.png',
        navigation: 'https://maps.app.goo.gl/AXWTNaZcf21UXbTY8',
        guests: 2,
        comingSoon: true,
      },
    ],
  },
  {
    id: "phase-2",
    title: "Phase II",
    description:
      "Located a few kilometers away from Keeth House Phase 1, the secluded property boasts four charming houses each with its unique attributes. The high ceilings of the cottages along with the lush tree cover across the expansive land create a cool and serene atmosphere both inside and out. The verdant setting with vibrant flora and fauna makes Keeth House Phase 2 a paradise for nature lovers.",
    houses: [
      {
        id: "keeth-house-4",
        propertyId: 7860,
        name: "Keeth House - IV",
        description:
          "The charming cottage, which efficiently combines the best features of all our houses, is best suited for couples seeking a quiet nature retreat. The high thatched roof and large windows with gorgeous views make the interiors spacious and airy without compromising on comfort. \n\n As you walk up the stone path to the house you are greeted by a small sit-out area facing the garden, where you can spend your mornings and evenings sipping coffee and enjoying your favorite novel. \n\n Inside the house is a small kitchen area with basic cookware and appliances. Next to it rests the locally made, comfortable wooden sofa and coffee table for you to lounge in. A partition made of stone and cement is raised in the middle of the room to separate the bedroom from the seating area. The bathroom built with walls made of cement and stone is accommodated in one corner of the room. \n\n A large triangular window that illuminates the whole room and the elevated balcony-type space next to it are the highlights of this cottage. It’s a beautiful spot to recline and gaze at the sky as the sun goes down and stars fill the space.",
        images: [
          "/images/keeth-house-iv/1.jpg",
          "/images/keeth-house-iv/2.jpg",
          "/images/keeth-house-iv/3.jpg",
          "/images/keeth-house-iv/4.jpg",
          "/images/keeth-house-iv/5.jpg",
          "/images/keeth-house-iv/6.jpg",
          "/images/keeth-house-iv/7.jpg",
          "/images/keeth-house-iv/8.jpg",
          "/images/keeth-house-iv/9.jpg",
          "/images/keeth-house-iv/10.jpg",
          "/images/keeth-house-iv/11.jpg",
          "/images/keeth-house-iv/12.jpg",
          "/images/keeth-house-iv/13.jpg",
          "/images/keeth-house-iv/14.jpg",
          "/images/keeth-house-iv/15.jpg",
          "/images/keeth-house-iv/16.jpg",
          "/images/keeth-house-iv/17.jpg",
          "/images/keeth-house-iv/18.jpg",
          "/images/keeth-house-iv/19.jpg",
          "/images/keeth-house-iv/20.jpg",
          "/images/keeth-house-iv/21.jpg",
          "/images/keeth-house-iv/22.jpg",
          "/images/keeth-house-iv/23.jpg",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Garden View", icon: TreePine },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Outdoor Dining", icon: Umbrella },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8',
        guests: 2,
      },
      {
        id: "keeth-house-5",
        propertyId: 7860,
        name: "Keeth House - V",
        description:
          "One of our biggest houses, this cottage symbolizes rustic elegance. With a bathtub inside and an outdoor shower in the backyard, you are sure to enjoy a luxurious stay with your loved one. \n\n Unlike other houses, this cottage does not follow the usual shape. It is designed and built to maximize the space without disturbing the majestic trees strewn across the plot. It has a spacious courtyard at the entrance with ample seating for you to relax and enjoy the crisp air. As you walk inside, you can find an adequately equipped kitchenette along with a table from where you can dine or work. \n\n Going further inside there’s a bedroom with a king-size bed perfect for a party of two. The expansive washroom has a large cement bathtub where you can relax in the warm, soothing water, and enjoy a refreshing bath that will melt your troubles away. Walking through the doorway to the backyard you can find an outdoor shower enveloped by cement bars and an open roof to provide privacy while retaining the natural atmosphere.",
        images: [
          "/images/keeth-house-v/1.jpg",
          "/images/keeth-house-v/2.jpg",
          "/images/keeth-house-v/3.jpg",
          "/images/keeth-house-v/4.jpg",
          "/images/keeth-house-v/5.jpg",
          "/images/keeth-house-v/6.jpg",
          "/images/keeth-house-v/7.jpg",
          "/images/keeth-house-v/8.jpg",
          "/images/keeth-house-v/9.jpg",
          "/images/keeth-house-v/10.jpg",
          "/images/keeth-house-v/11.jpg",
          "/images/keeth-house-v/12.jpg",
          "/images/keeth-house-v/13.jpg",
          "/images/keeth-house-v/14.jpg",
          "/images/keeth-house-v/15.jpg",
          "/images/keeth-house-v/16.jpg",
          "/images/keeth-house-v/17.jpg",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "Open Shower", icon: Droplets },
          { name: "Portico", icon: Umbrella },
          { name: "Garden View", icon: TreePine },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8',
        guests: 2,
      },
      {
        id: "keeth-house-6",
        propertyId: 7860,
        name: "Keeth House - VI",
        description:
          "The idyllic setting and unique design of the cottage make it a blissful retreat, perfect for sipping drinks by the pond or hosting a cookout party with your friends. \n\n As you walk towards the house, you are greeted by a small, pristine pond at the front, exclusive to this cottage. It’s a tempting spot to dip your feet in, relax, and exchange stories with your friends. Whip out your culinary skills and have a cook-off at the open kitchen which is built right at the entrance. There’s a dining table and seating right next to the kitchen for you to enjoy a grand outdoor feast. \n\n Inside the house, the room is split into two by a partial stone wall to separate the seating area from one of the two king-size beds. The second bed is placed on the upper deck facing a large A-frame window showing off the beautiful landscape. The bathroom is again split into two with the shower, sink, and dressing area on one corner and the lavatory on the opposite side. Next to the bathroom is another pathway to the house leading you to the backyard. \n\n The high ceiling, two doorways, and several windows make the room open and well-ventilated, keeping you refreshed and rejuvenated.",
        images: [
          "/images/keeth-house-vi/1.jpg",
          "/images/keeth-house-vi/2.jpg",
          "/images/keeth-house-vi/3.jpg",
          "/images/keeth-house-vi/4.jpg",
          "/images/keeth-house-vi/5.jpg",
          "/images/keeth-house-vi/6.jpg",
          "/images/keeth-house-vi/7.jpg",
          "/images/keeth-house-vi/8.jpg",
          "/images/keeth-house-vi/9.jpg",
          "/images/keeth-house-vi/10.jpg",
          "/images/keeth-house-vi/11.jpg",
          "/images/keeth-house-vi/12.jpg",
          "/images/keeth-house-vi/13.jpg",
          "/images/keeth-house-vi/14.jpg",
          "/images/keeth-house-vi/15.jpg",
          "/images/keeth-house-vi/16.jpg",
          "/images/keeth-house-vi/17.jpg",
          "/images/keeth-house-vi/18.jpg",
          "/images/keeth-house-vi/19.jpg",
          "/images/keeth-house-vi/20.jpg",
          "/images/keeth-house-vi/21.jpg",
          "/images/keeth-house-vi/22.jpg",
          "/images/keeth-house-vi/23.jpg",
          "/images/keeth-house-vi/24.jpg",
          "/images/keeth-house-vi/25.jpg",
          "/images/keeth-house-vi/26.jpg",
          "/images/keeth-house-vi/27.jpg",
        ],
        specializations: [
          { name: "Family Friendly", icon: Users },
          { name: "Waterbody", icon: Waves },
          { name: "Garden View", icon: TreePine },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8',
        guests: 4,
      },
      {
        id: "khaya-nest",
        propertyId: 7860,
        name: "The Khaya Nest",
        description:
          "We took connecting with nature to another level - a level that’s 10 meters above the ground! Khaya Nest is our very own tree house built around the majestic African Mahogany tree also known as the ‘Khaya’ tree. Built with intricate planning and care, Khaya Nest will give you a unique, safe, and adventurous experience that you won’t forget. \n\n While the concept of living in a treehouse is not new to the community of Auroville, The Khaya Nest is the first property built for tourists and visitors in and around Pondicherry. Situated at approximately 10 meters above the ground, the treehouse is accessed by climbing a sturdy, helical staircase that is wrapped around the trunk allowing you to embrace the tree as you make your ascend. \n\n When you reach the top of the stairs, the floorboard of the house is skillfully engineered to act as a trapdoor that you can push up. As you climb onto the house, you are greeted by a spacious deck at the entrance where you are blessed with a panoramic view of the resplendent landscape. There’s no match for this spot where you can sprawl down at night and count the stars that shine so bright in the absence of city lights. \n\n Across the doorway is a room with a comfortable bed big enough for two people. Above the bed is a circular window intentionally placed to frame the beautiful sunsets in a picture-perfect moment. As the tree moves to the wind, the house gently sways with it cradling you into a peaceful slumber in the night. In the morning, as you wake up to the sound of leaves rustling against the wind and the sweet chirping of birds on the branches, you are assured to feel refreshed and rejuvenated. \n\n While the property is built to give you an authentic outdoorsy and tropical experience, we have included some minimal but effective amenities to cater to your comfort. A small kitchenette with basic utensils, a working sink, and a dining table with stools are accommodated in the room. A large wooden tray with a rope & pulley system is installed to get your food and luggage with ease without having to carry them up and down. The house also has a small balcony where a western toilet is placed for your convenience. \n\n Additionally, a separate washroom with an outdoor shower is built on the ground right next to the tree. The shower area is surrounded by a low wall made of mud and black limestone, providing privacy while still allowing you to enjoy the beauty of the serene atmosphere with its open roof. The interior of the washroom that is adorned with natural elements, and the tall foliage surrounding the space both inside and out further enhances the wilderness experience. As you take a shower, you can bask in the sunlight, feel the refreshing drizzles of rain, and listen to the soothing sounds of nature. At night, the soft glow of the moon and warm lights from the treehouse create a romantic ambiance, making bathing a truly transcendent experience.",
        images: [
          "/images/khaya-nest/1.jpg",
          "/images/khaya-nest/2.jpg",
          "/images/khaya-nest/3.jpg",
          "/images/khaya-nest/4.jpg",
          "/images/khaya-nest/5.jpg",
          "/images/khaya-nest/6.jpg",
          "/images/khaya-nest/7.jpg",
          "/images/khaya-nest/8.jpg",
          "/images/khaya-nest/9.jpg",
          "/images/khaya-nest/10.jpg",
          "/images/khaya-nest/11.jpg",
          "/images/khaya-nest/12.jpg",
          "/images/khaya-nest/13.jpg",
          "/images/khaya-nest/14.jpg",
          "/images/khaya-nest/15.jpg",
          "/images/khaya-nest/16.jpg",
          "/images/khaya-nest/17.jpg",
          "/images/khaya-nest/18.jpg",
          "/images/khaya-nest/19.jpg",
          "/images/khaya-nest/20.jpg",
          "/images/khaya-nest/21.jpg",
          "/images/khaya-nest/22.jpg",
          "/images/khaya-nest/23.jpg",
          "/images/khaya-nest/24.jpg",
          "/images/khaya-nest/25.jpg",
          "/images/khaya-nest/26.jpg",
          
        ],
        specializations: [
          { name: "Tree House", icon: TreePine },
          { name: "Open Shower", icon: Droplets },
          { name: "Forest View", icon: Trees },
          { name: "Balcony", icon: Umbrella },
        ],
         map: '/images/maps/Phase-II-Map.png',
        navigation: 'https://maps.app.goo.gl/XU2mB2xnxno23KVS8',
        guests: 2,
      },
    ],
  },
  {
    id: "phase-3",
    title: "Phase III",
    description:
      "Our newest collection of unique eco-houses, combining sustainable living with modern comforts and amenities.",
    houses: [
      {
        id: "keeth-house-7",
        propertyId: 9930,
        name: "Keeth House - VII",
        description:
          "The bedroom features classic red oxide flooring, keeping the space cool and timeless. Traditional keeth and vezhal roofing ensures natural ventilation, creating an airy, refreshing ambiance. A stay at Keeth House VII is an invitation to embrace simplicity, tradition, and the beauty of slow living",
        images: [
          "/images/keeth-house-vii/1.JPG",
          "/images/keeth-house-vii/2.JPG",
          "/images/keeth-house-vii/3.JPG",
          "/images/keeth-house-vii/4.JPG",
          "/images/keeth-house-vii/5.JPG",
          "/images/keeth-house-vii/6.JPG",
          "/images/keeth-house-vii/7.JPG",
          "/images/keeth-house-vii/8.JPG",
          "/images/keeth-house-vii/9.JPG",
          "/images/keeth-house-vii/10.JPG",
          "/images/keeth-house-vii/9.JPG",
          "/images/keeth-house-vii/10.JPG",
        ],
        specializations: [
          { name: "Balcony", icon: Umbrella },
          { name: "Outdoor Shower", icon: Droplets },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
          { name: "Forest View", icon: Trees },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
      {
        id: "keeth-house-8",
        propertyId: 9930,
        name: "Keeth House - VIII",
        description:
          "Keeth House VIII is a refreshing take in Keeth House living, opening directly to a private swimming pool that sets the tone for a nature-immersed stay. At its heart, an open-to-sky roof invites sunlight and rain indoors, blurring the line between shelter and sky. The house features a spacious bedroom and a warm dining area perfect for gathering and connecting. Designed for those who seek comfort without losing touch with the outdoors, Keeth House VIII offers a serene and elemental living experience.",
        images: [
          "/images/keeth-house-viii/1.jpg",
          "/images/keeth-house-viii/2.jpg",
          "/images/keeth-house-viii/3.jpg",
          "/images/keeth-house-viii/4.jpg",
          "/images/keeth-house-viii/5.jpg",
          "/images/keeth-house-viii/6.jpg",
          "/images/keeth-house-viii/7.jpg",
          "/images/keeth-house-viii/8.jpg",
          "/images/keeth-house-viii/9.jpg",
          "/images/keeth-house-viii/10.jpg"
        ],
        specializations: [
          { name: "Swimming Pool", icon: Waves },
          { name: "Family Friendly", icon: Users },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Bar Counter", icon: Martini },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 4,
      },
      {
        id: "keeth-house-9",
        propertyId: 9930,
        name: "Keeth House - IX",
        description:
          "At its heart is a kitchenette with an island counter, perfect for cooking, gathering, and sharing meals. The separate bedroom opens onto a private balcony, an ideal spot to soak in the sunrise or starlit sky. Adjacent, the shower area blends comfort with the outdoors. A high-ventilated roof and red oxide flooring keep the space naturally cool and airy. Keeth House IX invites you to slow down, reconnect with nature, and embrace the beauty of simple living.",
        images: [
          "/images/keeth-house-ix/1.JPG",
          "/images/keeth-house-ix/2.JPG",
          "/images/keeth-house-ix/3.JPG",
          "/images/keeth-house-ix/4.JPG",
          "/images/keeth-house-ix/5.JPG",
          "/images/keeth-house-ix/6.JPG",
          "/images/keeth-house-ix/7.JPG",
          "/images/keeth-house-ix/8.JPG",
          "/images/keeth-house-ix/9.JPG",
          "/images/keeth-house-ix/10.JPG",
        ],
        specializations: [
          { name: "Waterbody", icon: Waves },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Shower View", icon: Eye },
          { name: "MudHouse", icon: Home },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
      {
        id: "keeth-house-10",
        propertyId: 9930,
        name: "Keeth House - X",
        description:
          "Coming Soon - Keeth House X will stand elevated, offering a unique retreat in nature. The house will be thoughtfully divided into sections, with large windows framing lush greenery and filling the space with natural light.",
        images: [
          "/images/coming-soon.jpg?height=600&width=800&text=Coming Soon",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "Shower View", icon: Eye },
          { name: "Outdoor Kitchen", icon: UtensilsCrossed },
          { name: "Hammock", icon: Moon },
        ],
        comingSoon: true,
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
      {
        id: "de-cabin",
        propertyId: 9930,
        name: "De Cabin",
        description:
          "Wooden House provides 400 sq. ft. of cosy, comfortable space, ideal for up to 2 guests. The room's warm design and modern amenities create a tranquil retreat for relaxation. Whether you're here for a short or extended stay, the Wooden House offers a peaceful environment to unwind. Enjoy comfort and convenience in this inviting room, designed to make your stay enjoyable and memorable.",
        images: [
          "/images/de-cabin/1.JPG",
          "/images/de-cabin/2.JPG",
          "/images/de-cabin/3.JPG",
          "/images/de-cabin/4.JPG",
          "/images/de-cabin/5.JPG",
          "/images/de-cabin/6.JPG",
          "/images/de-cabin/7.JPG",
          "/images/de-cabin/8.JPG",
          "/images/de-cabin/9.JPG",
          "/images/de-cabin/10.JPG",
          "/images/de-cabin/11.JPG",
          "/images/de-cabin/12.JPG",
          "/images/de-cabin/13.JPG",
          "/images/de-cabin/14.JPG",
          "/images/de-cabin/15.JPG",
          "/images/de-cabin/16.JPG",
          "/images/de-cabin/17.JPG",
          "/images/de-cabin/18.JPG",
          "/images/de-cabin/19.JPG",
          "/images/de-cabin/20.JPG",
        ],
        specializations: [
          { name: "Wooden House", icon: Home },
          { name: "Open Shower", icon: Droplets },
          { name: "Bar Counter", icon: Martini },
          { name: "Fully Equipped", icon: UtensilsCrossed },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
      {
        id: "de-villa-1",
        propertyId: 9930,
        name: "De Villa I",
        description:
          "Villa I offers a charming retreat that blends tradition with modern comfort. The cozy living area flows into a well-equipped kitchenette, creating a warm and inviting space Dine outdoors under a roof, surrounded by nature’s soothing sounds. The tranquil bedroom, with a garden-facing bed and air conditioning, ensures restful sleep. A cozy window seat invites moments of reading or quiet reflection. \n\n The highlight is the open-to-the-sky white bathtub beneath a neem tree—perfect for a refreshing soak under sunlight or starlit skies. More than just a stay, De Villa I offers a serene escape to slow down, connect with nature, and find inspiration.",
        images: [
          "/images/de-villa-i/1.JPG",
          "/images/de-villa-i/2.JPG",
          "/images/de-villa-i/3.JPG",
          "/images/de-villa-i/4.JPG",
          "/images/de-villa-i/5.JPG",
          "/images/de-villa-i/6.JPG",
          "/images/de-villa-i/7.JPG",
          "/images/de-villa-i/8.JPG",
          "/images/de-villa-i/9.JPG",
          "/images/de-villa-i/10.JPG",
          "/images/de-villa-i/11.JPG",
          "/images/de-villa-i/12.JPG",
          "/images/de-villa-i/13.JPG",
          "/images/de-villa-i/14.JPG",
          "/images/de-villa-i/15.JPG",
          "/images/de-villa-i/16.JPG",
          "/images/de-villa-i/17.JPG",
          "/images/de-villa-i/18.JPG",
        ],
        specializations: [
          { name: "Bath Tub", icon: Bath },
          { name: "AC", icon: Thermometer },
          { name: "Kitchen", icon: UtensilsCrossed },
          { name: "Outdoor Dining", icon: Umbrella },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
      {
        id: "de-villa-2",
        propertyId: 9930,
        name: "De Villa II",
        description:
          "A unique highlight is the indoor bathroom that opens to the sky, letting you bathe under the moonlight or daylight. The cozy, air-conditioned bedroom ensures restful sleep, offering a cool escape from the tropical warmth. For ultimate relaxation, unwind in the hammock corner, perfect for reading or simply soaking in the sounds of nature. A stay at De Villa II is a blend of tradition and comfort, designed for peace and connection with nature.",
        images: [
          "/images/de-villa-ii/1.JPG",
          "/images/de-villa-ii/2.JPG",
          "/images/de-villa-ii/3.JPG",
          "/images/de-villa-ii/4.JPG",
          "/images/de-villa-ii/5.JPG",
          "/images/de-villa-ii/6.JPG",
          "/images/de-villa-ii/7.JPG",
          "/images/de-villa-ii/8.JPG",
          "/images/de-villa-ii/9.JPG",
          "/images/de-villa-ii/10.JPG",
          "/images/de-villa-ii/11.JPG",
          "/images/de-villa-ii/12.JPG",
          "/images/de-villa-ii/13.JPG",
          "/images/de-villa-ii/14.JPG",
        ],
        specializations: [
          { name: "Open Shower", icon: Droplets },
          { name: "AC", icon: Thermometer },
          { name: "Hammock", icon: Moon },
          { name: "Villa", icon: Building },
        ],
        map: '/images/maps/Phase-III-Map.png',
        navigation: 'https://maps.app.goo.gl/yjh3P49suiYNaVHS7',
        guests: 2,
      },
    ],
  },
];

// Flattened array of all houses for OurHouses component
export const houses = phaseData.reduce((acc, phase) => {
  return acc.concat(
    phase.houses.map((house) => ({
      ...house,
      location: phase.title,
      price: 150,
      phase: phase.title,
    }))
  );
}, []);
